# -*- coding: utf-8 -*-
"""main3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11a6i2mP9wWSTQMuGSdvkoX1qmZkYgpxP
"""

!pip install osmnx networkx numpy pandas scikit-learn tensorflow
!apt-get install sumo sumo-tools sumo-doc

import os

# Set SUMO_HOME environment variable
os.environ["SUMO_HOME"] = "/usr/share/sumo"

# Verify SUMO installation
!sumo --version

from google.colab import files

uploaded = files.upload()  # Select your OSM file when prompted

!ls

!netconvert --osm-files=kozhikode.osm --output-file=network.net.xml

import os
os.environ["SUMO_HOME"] = "/usr/share/sumo"  # Adjust path if necessary

!python3 /usr/share/sumo/tools/randomTrips.py -n network.net.xml -o trips.trips.xml -r routes.rou.xml

!sumo -n network.net.xml -r routes.rou.xml

!sumo -n network.net.xml -r routes.rou.xml --tripinfo-output tripinfo.xml

from google.colab import files
files.download("tripinfo.xml")

!sumo --step-length 1 -n network.net.xml -r routes.rou.xml --duration-log.statistics true

!sumo --time-to-teleport 600 -n network.net.xml -r routes.rou.xml

!sumo --time-to-teleport 1200 -n network.net.xml -r routes.rou.xml

!python3 /usr/share/sumo/tools/randomTrips.py -n network.net.xml -o trips.trips.xml -r routes.rou.xml --period 10

!python3 /usr/share/sumo/tools/xml/xml2csv.py network.net.xml

!ls

!head -n 20 network.net.csv

!grep "<tlLogic" network.net.xml

!python3 /usr/share/sumo/tools/xml/xml2csv.py network.net.xml

!ls

import xml.etree.ElementTree as ET

# Load the XML file
tree = ET.parse("network.net.xml")
root = tree.getroot()

# Find and modify all traffic lights
for tlLogic in root.findall("tlLogic"):
    for phase in tlLogic.findall("phase"):
        if "GGG" in phase.attrib["state"]:  # If this phase has a green light
            phase.attrib["duration"] = "45"  # Change the duration to 45s

# Save the modified XML file
tree.write("modified_network.net.xml")

# Check the first few lines to verify
!head -n 20 modified_network.net.xml

!grep "<tlLogic" network.net.xml

!grep -A 5 "<tlLogic" network.net.xml

!sumo-gui -n network.net.xml -r routes.rou.xml --save-traffic-lights tl_logic.xml

import xml.etree.ElementTree as ET

# Load the SUMO network XML file
tree = ET.parse("network.net.xml")
root = tree.getroot()

# Loop through all traffic lights and modify green light durations
for tlLogic in root.findall("tlLogic"):
    for phase in tlLogic.findall("phase"):
        if "G" in phase.attrib["state"]:  # If this phase has a green light
            phase.attrib["duration"] = "45"  # Increase green light duration to 45s

# Save the modified file
tree.write("modified_network.net.xml")

# Verify the changes
!head -n 20 modified_network.net.xml

!netconvert -s modified_network.net.xml -o new_network.net.xml

!grep -c "<vehicle" routes.rou.xml

!sumo -n new_network.net.xml -r routes.rou.xml

!sumo-gui -n new_network.net.xml -r routes.rou.xml

!sumo -n new_network.net.xml -r routes.rou.xml --tripinfo-output tripinfo_after.xml

from google.colab import files
files.download("tripinfo_after.xml")

!grep -o 'waitingTime="[0-9]*\.*[0-9]*"' tripinfo_after.xml | awk -F'"' '{sum+=$2; count++} END {print "Avg Waiting Time:", sum/count, "seconds"}'

!grep -o 'duration="[0-9]*\.*[0-9]*"' tripinfo_after.xml | awk -F'"' '{sum+=$2; count++} END {print "Avg Trip Duration:", sum/count, "seconds"}'

import xml.etree.ElementTree as ET
import matplotlib.pyplot as plt

# Load the XML file
tree = ET.parse("tripinfo_after.xml")
root = tree.getroot()

# Extract waiting times and durations
waiting_times = []
durations = []

for trip in root.findall("tripinfo"):
    waiting_times.append(float(trip.attrib["waitingTime"]))
    durations.append(float(trip.attrib["duration"]))

# Plot the results
plt.figure(figsize=(10,5))
plt.hist(waiting_times, bins=50, alpha=0.7, label="Waiting Time")
plt.hist(durations, bins=50, alpha=0.7, label="Trip Duration")
plt.xlabel("Time (seconds)")
plt.ylabel("Number of Vehicles")
plt.legend()
plt.title("Traffic Performance After Optimization")
plt.show()

import xml.etree.ElementTree as ET
import matplotlib.pyplot as plt

# Load the XML file for BEFORE optimization
tree = ET.parse("tripinfo.xml")  # This is the original simulation output
root = tree.getroot()

# Extract waiting times and durations
waiting_times_before = []
durations_before = []

for trip in root.findall("tripinfo"):
    waiting_times_before.append(float(trip.attrib["waitingTime"]))
    durations_before.append(float(trip.attrib["duration"]))

# Plot the results
plt.figure(figsize=(10,5))
plt.hist(waiting_times_before, bins=50, alpha=0.7, label="Waiting Time (Before)")
plt.hist(durations_before, bins=50, alpha=0.7, label="Trip Duration (Before)")
plt.xlabel("Time (seconds)")
plt.ylabel("Number of Vehicles")
plt.legend()
plt.title("Traffic Performance Before Optimization")
plt.show()

!grep -o 'waitingTime="[0-9]*\.*[0-9]*"' tripinfo.xml | awk -F'"' '{sum+=$2; count++} END {print "Avg Waiting Time:", sum/count, "seconds"}'
!grep -o 'duration="[0-9]*\.*[0-9]*"' tripinfo.xml | awk -F'"' '{sum+=$2; count++} END {print "Avg Trip Duration:", sum/count, "seconds"}'

import xml.etree.ElementTree as ET
import pandas as pd

# Load tripinfo_after.xml
tree = ET.parse("tripinfo_after.xml")
root = tree.getroot()

# Create an empty list for storing data
data = []

# Extract relevant fields
for trip in root.findall("tripinfo"):
    vehicle_id = trip.attrib["id"]
    duration = float(trip.attrib["duration"])
    waiting_time = float(trip.attrib["waitingTime"])

    # Store in list
    data.append([vehicle_id, duration, waiting_time])

# Convert to DataFrame
df = pd.DataFrame(data, columns=["Vehicle ID", "Trip Duration", "Waiting Time"])

# Save to CSV
df.to_csv("traffic_data.csv", index=False)

# Show the first few rows
print(df.head())

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

# Load data
df = pd.read_csv("traffic_data.csv")

# Define input (features) and output (target)
X = df[["Waiting Time", "Trip Duration"]]  # Features
y = df["Waiting Time"] * 0.5  # Target: Approximate light duration

# Split dataset for training/testing (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Linear Regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict on test data
y_pred = model.predict(X_test)

# Evaluate the model
mae = mean_absolute_error(y_test, y_pred)
print(f"Model MAE (Lower is better): {mae}")

# Save the trained model
import pickle
with open("traffic_model.pkl", "wb") as f:
    pickle.dump(model, f)

print("Model training complete. Saved as traffic_model.pkl")

print(model.feature_names_in_)  # Shows the expected column names

import pandas as pd

# Fix column order to match model training
new_traffic = pd.DataFrame([[15, 120]], columns=["Waiting Time", "Trip Duration"])

# Predict best light duration
predicted_duration = model.predict(new_traffic)[0]
print(f"Suggested Green Light Duration: {predicted_duration:.2f} seconds ✅")

import xml.etree.ElementTree as ET
import pandas as pd

# Load the trained model
import pickle
with open("traffic_model.pkl", "rb") as f:
    model = pickle.load(f)

# Load SUMO network XML file
tree = ET.parse("network.net.xml")
root = tree.getroot()

# Iterate through all traffic lights and update green light durations
for tlLogic in root.findall("tlLogic"):
    for phase in tlLogic.findall("phase"):
        if "G" in phase.attrib["state"]:  # If this phase has a green light
            # Example: Use waiting time of 15s & trip duration of 120s for prediction
            traffic_conditions = pd.DataFrame([[15, 120]], columns=["Waiting Time", "Trip Duration"])
            predicted_time = model.predict(traffic_conditions)[0]

            # Update duration in the XML file
            phase.attrib["duration"] = str(round(predicted_time))

# Save the new SUMO network file with ML-based traffic light durations
tree.write("optimized_network.net.xml")

print(" SUMO traffic lights updated using ML model predictions!")

!netconvert -s optimized_network.net.xml -o final_network.net.xml

!sumo -n final_network.net.xml -r routes.rou.xml --tripinfo-output tripinfo_ml.xml

from google.colab import files
files.download("tripinfo_ml.xml")

!grep -o 'waitingTime="[0-9]*\.*[0-9]*"' tripinfo_ml.xml | awk -F'"' '{sum+=$2; count++} END {print "Avg Waiting Time:", sum/count, "seconds"}'

!grep -o 'duration="[0-9]*\.*[0-9]*"' tripinfo_ml.xml | awk -F'"' '{sum+=$2; count++} END {print "Avg Trip Duration:", sum/count, "seconds"}'

!pip install --upgrade osmnx

import osmnx as ox
import geopandas as gpd

# Define the city or area from OSM
place_name = "Kozhikode, India"

# Get OSM buildings using the correct function
buildings = ox.features_from_place(place_name, tags={"building": True})

# Save as GeoJSON or CSV for EnergyPlus
buildings.to_file("buildings.geojson", driver="GeoJSON")
buildings.to_csv("buildings.csv")

print(" Extracted building data from OSM!")

!pip install eppy

import eppy
print(" Eppy is installed correctly!")

import eppy
print(eppy.__version__)

import eppy
import os
print(os.path.dirname(eppy.__file__))

import os
print(os.listdir("/usr/local/lib/python3.11/dist-packages/eppy"))

from eppy.modeleditor import IDF  # Alternative import

import sys
sys.path.append("/usr/local/lib/python3.11/dist-packages")

from eppy.modeleditor import IDF  # Try import again

print(IDF)

import eppy
print(dir(eppy))

from eppy.modeleditor import IDF
print(IDF)

idd_file = "/path/to/Energy+.idd"  # Change this to the correct path
IDF.setiddname(idd_file)
print(" IDD file loaded successfully!")

import osmnx as ox
import geopandas as gpd

# Define the city or area of interest
place_name = "Kozhikode, India"

# Get OSM building footprints
buildings = ox.features_from_place(place_name, tags={"building": True})

# Save as GeoJSON
buildings.to_file("buildings.geojson", driver="GeoJSON")

print(" Extracted and saved building data!")

import osmnx as ox
import geopandas as gpd
import matplotlib.pyplot as plt

# Load the extracted building data
buildings = gpd.read_file("buildings.geojson")

# Plot buildings
fig, ax = plt.subplots(figsize=(10, 10))
buildings.plot(ax=ax, color="lightblue", edgecolor="black")
plt.title("Building Footprints - Kozhikode")
plt.show()

import osmnx as ox
import geopandas as gpd

# Define the place of interest
place_name = "Kozhikode, India"

# Extract buildings from OSM
buildings = ox.features_from_place(place_name, tags={"building": True})

# Convert to a projected CRS (UTM Zone 43N for India)
buildings = buildings.to_crs(epsg=32643)

# Compute building area and centroid
buildings["area"] = buildings.geometry.area
buildings["centroid"] = buildings.geometry.centroid

# Keep only one geometry column before saving
centroids = buildings[["centroid"]]  # Separate centroids
buildings = buildings.drop(columns=["centroid"])  # Drop extra geometry

# Save the buildings with area
buildings.to_file("buildings_with_features.geojson", driver="GeoJSON")
centroids.to_file("building_centroids.geojson", driver="GeoJSON")

print(" Fixed CRS, computed areas, and saved files correctly!")

import matplotlib.pyplot as plt
import osmnx as ox
import geopandas as gpd

# Load the processed building dataset
buildings = gpd.read_file("buildings_with_features.geojson")

# Plot buildings with color based on area
fig, ax = plt.subplots(figsize=(10, 10))
buildings.plot(ax=ax, column="area", cmap="viridis", legend=True, alpha=0.7)

plt.title(" Building Layout & Area Distribution")
plt.show()

# Get the road network
graph = ox.graph_from_place("Kozhikode, India", network_type="drive")
roads = ox.graph_to_gdfs(graph, nodes=False, edges=True)

# Plot buildings + roads
fig, ax = plt.subplots(figsize=(10, 10))
buildings.plot(ax=ax, column="area", cmap="viridis", legend=True, alpha=0.7)
roads.plot(ax=ax, color="black", linewidth=0.5, alpha=0.6)

plt.title(" Building Layout with Road Network")
plt.show()

import geopandas as gpd
import numpy as np
from scipy.spatial import cKDTree

# Load building data
buildings = gpd.read_file("buildings_with_features.geojson")

# Convert centroids to NumPy array
centroids = np.array(list(zip(buildings.geometry.centroid.x, buildings.geometry.centroid.y)))

# Build a KDTree for fast nearest neighbor search
tree = cKDTree(centroids)

# Query the nearest neighbors (excluding self)
distances, indices = tree.query(centroids, k=2)  # k=2 because first is self, second is nearest neighbor
buildings["nearest_distance"] = distances[:, 1]  # Take the second nearest

# Compute density
total_area = buildings["area"].sum()
building_count = len(buildings)
density = building_count / total_area

print(f" Total Buildings: {building_count}")
print(f" Average Distance Between Buildings: {buildings['nearest_distance'].mean():.2f} meters")
print(f" Building Density: {density:.4f} buildings per unit area")

import geopandas as gpd
import numpy as np
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

# Load building data
buildings = gpd.read_file("buildings_with_features.geojson")

# Extract relevant features (centroids, area)
X = np.array(list(zip(buildings.geometry.centroid.x, buildings.geometry.centroid.y, buildings["area"])))

# Apply K-Means Clustering (choose 5 clusters)
kmeans = KMeans(n_clusters=5, random_state=42, n_init=10)
buildings["cluster"] = kmeans.fit_predict(X)

# Plot clusters
plt.figure(figsize=(10, 6))
for cluster in range(5):
    subset = buildings[buildings["cluster"] == cluster]
    plt.scatter(subset.geometry.centroid.x, subset.geometry.centroid.y, label=f"Cluster {cluster}", alpha=0.5)

plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.legend()
plt.title("Building Clustering for Zoning")
plt.show()

# Save updated file
buildings.to_file("buildings_clustered.geojson", driver="GeoJSON")
print(" Clustering Completed & Saved!")

import osmnx as ox
print(ox.__version__)

import osmnx as ox
import networkx as nx
import geopandas as gpd
import matplotlib.pyplot as plt

# Step 1: Define the city and load road network
place_name = "Kozhikode, India"
G = ox.graph_from_place(place_name, network_type="drive")
G = ox.project_graph(G)  # Project to UTM for accurate distance measures

# Step 2: Load clustered building data and match CRS
buildings = gpd.read_file("buildings_clustered.geojson")
buildings = buildings.to_crs(G.graph['crs'])  # Ensure same CRS as road network

# Step 3: Compute centroids and get one representative building per cluster
buildings["centroid"] = buildings.geometry.centroid

# Avoid deprecated groupby.apply
representatives = (
    buildings.loc[buildings.groupby("cluster")["area"].idxmax()]
    .copy()
    .reset_index(drop=True)
)

# Step 4: Find nearest road network node for each representative building
nearest_nodes = [
    ox.distance.nearest_nodes(G, point.x, point.y)
    for point in representatives["centroid"]
]

# Step 5: Compute shortest path lengths between each cluster
shortest_paths = {}
for i, node1 in enumerate(nearest_nodes):
    for j, node2 in enumerate(nearest_nodes):
        if i < j:
            try:
                length = nx.shortest_path_length(G, node1, node2, weight="length")
                shortest_paths[(i, j)] = length
            except nx.NetworkXNoPath:
                shortest_paths[(i, j)] = float("inf")  # No path exists

# Step 6: Compute accessibility scores (sum of path lengths to all other clusters)
accessibility_scores = {
    i: sum([
        shortest_paths.get((min(i, j), max(i, j)), float("inf"))
        for j in range(len(nearest_nodes)) if i != j
    ])
    for i in range(len(nearest_nodes))
}

# Step 7: Rank clusters by accessibility (lower score = better access)
sorted_clusters = sorted(accessibility_scores, key=accessibility_scores.get)

print(" Accessibility Ranking of Clusters:")
for rank, cluster in enumerate(sorted_clusters):
    print(f"Rank {rank+1}: Cluster {cluster} (Score: {accessibility_scores[cluster]:.2f})")

# Step 8: Plot road network + building clusters
fig, ax = plt.subplots(figsize=(12, 10))
ox.plot_graph(G, ax=ax, node_size=0, edge_linewidth=0.6, edge_color="gray", show=False, close=False)
buildings.plot(ax=ax, column="cluster", cmap="tab10", alpha=0.6, edgecolor="black")
plt.title(" Kozhikode: Road Network + Building Clusters")
plt.show()

print(" Road Network Accessibility Analysis Done!")

import geopandas as gpd

# Load the building data
buildings = gpd.read_file("buildings_clustered.geojson")

# ✅ Step 1: If CRS is missing, set it to WGS84 (EPSG:4326)
if buildings.crs is None:
    print(" No CRS found! Setting default CRS (EPSG:4326).")
    buildings.set_crs(epsg=4326, inplace=True)

# ✅ Step 2: Now estimate UTM (this will now work)
try:
    utm_crs = buildings.estimate_utm_crs()
    buildings = buildings.to_crs(utm_crs)
    print(f"Converted to UTM CRS: {utm_crs}")
except RuntimeError:
    # Fallback: manually set CRS to UTM Zone 43N (India region)
    print(" Auto-detection failed! Setting CRS to EPSG:32643 (UTM Zone 43N)")
    buildings = buildings.to_crs(epsg=32643)

import geopandas as gpd

# Load building data
buildings = gpd.read_file("buildings_clustered.geojson")

# Step 1: Set CRS to WGS84 if missing
if buildings.crs is None:
    print(" No CRS found. Setting to WGS84 (EPSG:4326).")
    buildings.set_crs(epsg=4326, inplace=True)

# Step 2: Manually project to UTM Zone 43N (EPSG:32643)
print(" Converting to UTM Zone 43N (EPSG:32643)...")
buildings = buildings.to_crs(epsg=32643)

# Step 3: Save and confirm
buildings.to_file("utm_buildings.geojson", driver="GeoJSON")
print(f" Converted and saved buildings with CRS: {buildings.crs}")

import numpy as np

buildings["centroid"] = buildings.geometry.centroid
buildings["area_m2"] = buildings.geometry.area

import geopandas as gpd
import osmnx as ox
import matplotlib.pyplot as plt
import warnings

# Ignore warnings from shapefiles
warnings.filterwarnings("ignore", category=RuntimeWarning)

# Load clustered buildings
buildings = gpd.read_file("buildings_clustered.geojson")

# Step 1: Ensure CRS is set (EPSG:4326 - WGS84)
if buildings.crs is None:
    print(" No CRS found. Setting default CRS to EPSG:4326 (WGS84).")
    buildings.set_crs(epsg=4326, inplace=True)

# Step 2: Convert manually to UTM Zone 43N (EPSG:32643)
print(" Projecting to UTM Zone 43N (EPSG:32643)...")
buildings = buildings.to_crs(epsg=32643)
print(f" Projected CRS: {buildings.crs}")

# Step 3: Compute geometry metrics
buildings["area_m2"] = buildings.geometry.area
buildings["centroid"] = buildings.geometry.centroid

# Optional: Save centroids separately
centroids = gpd.GeoDataFrame(geometry=buildings["centroid"], crs=buildings.crs)
centroids.to_file("building_centroids.geojson", driver="GeoJSON")

# Drop centroid geometry column before saving full buildings
buildings = buildings.drop(columns=["centroid"])
buildings.to_file("utm_buildings.geojson", driver="GeoJSON")

print(" Saved: utm_buildings.geojson and building_centroids.geojson")

import geopandas as gpd

# Load building centroids
centroids = gpd.read_file("building_centroids.geojson")

# Step 1: Ensure CRS is defined
if centroids.crs is None:
    print(" CRS not found. Setting to EPSG:4326 (WGS84)...")
    centroids.set_crs(epsg=4326, inplace=True)

# Step 2: Project manually to UTM Zone 43N (EPSG:32643)
print(" Projecting to UTM CRS (EPSG:32643)...")
centroids = centroids.to_crs(epsg=32643)

# Step 3: Confirm
print(f"CRS is now: {centroids.crs}")

import numpy as np
from scipy.spatial import cKDTree

# Convert centroids to NumPy array
coords = np.array(list(zip(centroids.geometry.x, centroids.geometry.y)))

# Build KDTree for fast distance computation
tree = cKDTree(coords)

# Find nearest neighbor distances (excluding self)
distances, _ = tree.query(coords, k=2)
centroids["nearest_distance"] = distances[:, 1]  # Skip self (index 0)

# Calculate density
total_area = centroids.shape[0]  # 1 building = 1 unit
bbox_area = centroids.total_bounds  # bounding box of the area
width = bbox_area[2] - bbox_area[0]
height = bbox_area[3] - bbox_area[1]
area = width * height
density = len(centroids) / area

print(f"Total buildings: {len(centroids)}")
print(f" Avg. nearest neighbor distance: {centroids['nearest_distance'].mean():.2f} meters")
print(f" Estimated building density: {density:.4f} buildings per m²")

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

# Prepare features for clustering: X, Y coordinates
X = np.array(list(zip(centroids.geometry.x, centroids.geometry.y)))

# Run KMeans clustering (e.g., 5 clusters)
kmeans = KMeans(n_clusters=5, random_state=42, n_init=10)
centroids["cluster"] = kmeans.fit_predict(X)

# Visualize clusters
plt.figure(figsize=(10, 6))
for c in range(5):
    cluster_data = centroids[centroids["cluster"] == c]
    plt.scatter(cluster_data.geometry.x, cluster_data.geometry.y, label=f"Cluster {c}", alpha=0.6)

plt.title(" Building Clusters (KMeans)")
plt.xlabel("X")
plt.ylabel("Y")
plt.legend()
plt.grid(True)
plt.show()

# Save clustered centroids as GeoJSON
centroids.to_file("clustered_centroids.geojson", driver="GeoJSON")
print("💾 Saved clustered centroid data as clustered_centroids.geojson")

import geopandas as gpd

# Load original buildings for context
buildings = gpd.read_file("utm_buildings.geojson")

# Merge building polygons with cluster info
buildings["cluster"] = centroids["cluster"].values  # align by index

# Plot full layout with clusters
fig, ax = plt.subplots(figsize=(10, 10))
buildings.plot(ax=ax, column="cluster", cmap="Set2", legend=True, edgecolor="black", alpha=0.6)
plt.title(" Building Footprints Colored by Cluster")
plt.show()

import osmnx as ox
import matplotlib.pyplot as plt
import geopandas as gpd

# Load clustered buildings and road network
buildings = gpd.read_file("buildings_clustered.geojson")
graph = ox.graph_from_place("Kozhikode, India", network_type="drive")
roads = ox.graph_to_gdfs(graph, nodes=False, edges=True)

# Plot layout
fig, ax = plt.subplots(figsize=(12, 10))
buildings.plot(ax=ax, column="cluster", cmap="Set2", edgecolor="black", alpha=0.6)
roads.plot(ax=ax, color="gray", linewidth=0.5)
plt.title(" Optimized Urban Layout: Clusters + Road Network")
plt.show()

import osmnx as ox
import geopandas as gpd
import matplotlib.pyplot as plt

# Load the clustered building layout
buildings = gpd.read_file("buildings_clustered.geojson")

# Load road network
place = "Kozhikode, India"
graph = ox.graph_from_place(place, network_type="drive")
graph_proj = ox.project_graph(graph)

# Convert road graph to GeoDataFrame
edges = ox.graph_to_gdfs(graph_proj, nodes=False, edges=True)

# Ensure CRS matches
buildings = buildings.to_crs(edges.crs)

fig, ax = plt.subplots(figsize=(12, 10))

# Plot buildings by cluster
buildings.plot(ax=ax, column="cluster", cmap="Set2", legend=True, alpha=0.6, edgecolor="black")

# Plot roads on top
edges.plot(ax=ax, color="gray", linewidth=0.5)

plt.title(" Optimized Layout: Buildings + Road Network (Zoned Clusters)")
plt.axis("off")
plt.show()

import xml.etree.ElementTree as ET
import pandas as pd
from shapely.geometry import Point

# Load SUMO network XML
tree = ET.parse("final_network.net.xml")
root = tree.getroot()

# Extract nodes with traffic lights
tls_nodes = []
for node in root.findall("node"):
    if node.attrib.get("type") == "traffic_light":
        x = float(node.attrib["x"])
        y = float(node.attrib["y"])
        tls_nodes.append(Point(x, y))

# Convert to GeoDataFrame
traffic_lights = gpd.GeoDataFrame(geometry=tls_nodes, crs="EPSG:32643")
traffic_lights = traffic_lights.to_crs(edges.crs)

fig, ax = plt.subplots(figsize=(12, 10))

# Plot everything together
buildings.plot(ax=ax, column="cluster", cmap="Set2", legend=True, edgecolor="black", alpha=0.6)
edges.plot(ax=ax, color="gray", linewidth=0.5)
traffic_lights.plot(ax=ax, color="red", markersize=30, label=" Traffic Lights")

plt.title(" Optimized Urban Layout with Buildings, Roads & Traffic Lights")
plt.legend()
plt.axis("off")
plt.show()

import geopandas as gpd
import osmnx as ox
import matplotlib.pyplot as plt
import xml.etree.ElementTree as ET
from shapely.geometry import Point

# Load raw buildings and clustered buildings
raw_buildings = gpd.read_file("utm_buildings.geojson")
clustered_buildings = gpd.read_file("buildings_clustered.geojson")

# Load road network
place = "Kozhikode, India"
G = ox.graph_from_place(place, network_type="drive")
G_proj = ox.project_graph(G)
roads = ox.graph_to_gdfs(G_proj, nodes=False, edges=True)

# Match CRS for both building sets
raw_buildings = raw_buildings.to_crs(roads.crs)
clustered_buildings = clustered_buildings.to_crs(roads.crs)

# Load final optimized SUMO network
tree = ET.parse("final_network.net.xml")
root = tree.getroot()

# Get traffic light node positions
tls_nodes = []
for node in root.findall("node"):
    if node.attrib.get("type") == "traffic_light":
        x, y = float(node.attrib["x"]), float(node.attrib["y"])
        tls_nodes.append(Point(x, y))

# Convert to GeoDataFrame
traffic_lights = gpd.GeoDataFrame(geometry=tls_nodes, crs="EPSG:32643")
traffic_lights = traffic_lights.to_crs(roads.crs)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(20, 10))

# BEFORE Optimization
raw_buildings.plot(ax=ax1, color="lightgray", edgecolor="black", alpha=0.7)
roads.plot(ax=ax1, color="gray", linewidth=0.5)
ax1.set_title(" BEFORE Optimization\n(Original OSM Layout)")
ax1.axis("off")

# AFTER Optimization
clustered_buildings.plot(ax=ax2, column="cluster", cmap="Set2", edgecolor="black", legend=True, alpha=0.6)
roads.plot(ax=ax2, color="gray", linewidth=0.5)
traffic_lights.plot(ax=ax2, color="red", markersize=40, label="🚦 Traffic Lights")
ax2.set_title(" AFTER Optimization\n(Zones + Roads + ML Traffic Lights)")
ax2.legend()
ax2.axis("off")

plt.tight_layout()
plt.show()

import geopandas as gpd
import matplotlib.pyplot as plt

# Assuming these are loaded:
# raw_buildings: GeoDataFrame before optimization
# clustered_buildings: GeoDataFrame after clustering
# Both must be in same CRS and indexed similarly for comparison

# Optional: align them by nearest building if IDs are not same
# For simplicity, we'll compare geometries and centroids

raw_centroids = raw_buildings.copy()
raw_centroids["geometry"] = raw_centroids.centroid

clustered_centroids = clustered_buildings.copy()
clustered_centroids["geometry"] = clustered_centroids.centroid

# Find moved or reassigned buildings (based on cluster changes)
diff = clustered_buildings.copy()
diff["changed"] = raw_buildings["geometry"] != clustered_buildings["geometry"]

# Plot the differences
fig, ax = plt.subplots(1, 1, figsize=(12, 12))

# Plot roads
roads.plot(ax=ax, color="lightgray", linewidth=0.5)

# Buildings before (gray)
raw_centroids.plot(ax=ax, color="black", markersize=5, label="Before")

# Changed buildings after (highlighted)
changed = diff[diff["changed"]]
changed.plot(ax=ax, color="red", markersize=10, label="Changed After")

# Unchanged (optional)
unchanged = diff[~diff["changed"]]
unchanged.plot(ax=ax, color="blue", markersize=5, alpha=0.3, label="Unchanged")

plt.title(" Building Changes After Optimization")
plt.legend()
plt.axis("off")
plt.show()

!pip install geopandas shapely

if 'optimized_roads' in globals():
    optimized_roads.to_file("optimized_roads.geojson", driver="GeoJSON")
    print(" File saved successfully!")
else:
    print(" optimized_roads is not defined. Run the road generation steps first.")


print(os.path.exists("optimized_roads.geojson"))

import geopandas as gpd
from xml.etree.ElementTree import Element, SubElement, ElementTree

# Load optimized roads (assuming you've already created `optimized_roads`)
optimized_roads = gpd.read_file("optimized_roads.geojson")

# Convert to WGS 84 (EPSG:4326) for OSM compatibility
optimized_roads = optimized_roads.to_crs(epsg=4326)

# Create OSM XML structure
osm = Element("osm", version="0.6", generator="GeoPandas")

# Temporary negative IDs (OSM requires unique node/way IDs)
node_id = -1
nodes = {}

for i, line in enumerate(optimized_roads.geometry):
    way = SubElement(osm, "way", id=str(-i - 1))

    for point in line.coords:
        if point not in nodes:
            nodes[point] = node_id
            node = SubElement(osm, "node", id=str(node_id), lat=str(point[1]), lon=str(point[0]))  # FIXED LAT/LON
            node_id -= 1  # Ensure unique ID

        nd = SubElement(way, "nd", ref=str(nodes[point]))

    # Add a basic road tag
    SubElement(way, "tag", k="highway", v="unclassified")

# Save as OSM file
osm_file = "optimized_roads.osm"
tree = ElementTree(osm)
tree.write(osm_file, encoding="utf-8", xml_declaration=True)

print(f" OSM file saved: {osm_file}")

import osmnx as ox

place_name = "Kozhikode, India"  # Change to your location
existing_roads = ox.graph_from_place(place_name, network_type="all")
gdf_edges = ox.graph_to_gdfs(existing_roads, nodes=False)  # Extract roads

# Save and reload
gdf_edges.to_file("existing_roads.geojson", driver="GeoJSON")
existing_roads = gpd.read_file("existing_roads.geojson").to_crs(epsg=4326)

print(" Existing roads downloaded and saved!")

import geopandas as gpd
import matplotlib.pyplot as plt
from shapely.geometry import LineString, Point
from scipy.spatial import Delaunay
import numpy as np
import networkx as nx
from xml.etree.ElementTree import Element, SubElement, ElementTree
from sklearn.neighbors import NearestNeighbors

# --- Load Building Centroids ---
centroids = gpd.read_file("building_centroids.geojson")
centroids = centroids.to_crs(epsg=32643)  # Convert to UTM for distance calculations

# Extract coordinates
points = np.array([[geom.x, geom.y] for geom in centroids.geometry])

# --- Step 1: Delaunay Triangulation (Initial Network) ---
tri = Delaunay(points)
edges = set()
for simplex in tri.simplices:
    for i in range(3):
        edge = tuple(sorted((simplex[i], simplex[(i+1) % 3])))
        edges.add(edge)

# Convert edges to LineString and filter by length
min_length = 50   # Minimum road length
max_length = 500  # Maximum road length

road_lines = []
graph = nx.Graph()
for i, j in edges:
    line = LineString([points[i], points[j]])
    length = line.length
    if min_length < length < max_length:  # Keep only roads in a reasonable range
        road_lines.append(line)
        graph.add_edge(i, j, weight=length)

# --- Step 2: Compute Minimum Spanning Tree (MST) ---
mst_edges = list(nx.minimum_spanning_edges(graph, data=False))
mst_lines = [LineString([points[i], points[j]]) for i, j in mst_edges]

# --- Step 3: Ensure Full Connectivity Using KNN ---
k = 3  # Number of nearest neighbors (adjust if needed)
nbrs = NearestNeighbors(n_neighbors=k, algorithm="ball_tree").fit(points)
distances, indices = nbrs.kneighbors(points)

extra_connections = []
for i, neighbors in enumerate(indices):
    for j in neighbors:
        if i != j and not graph.has_edge(i, j):  # Add only if not already connected
            line = LineString([points[i], points[j]])
            if line.length < max_length:  # Avoid excessively long roads
                extra_connections.append(line)
                graph.add_edge(i, j, weight=line.length)

# --- Step 4: Final Optimized Road Network ---
final_road_lines = mst_lines + extra_connections
optimized_roads = gpd.GeoDataFrame(geometry=final_road_lines, crs="EPSG:32643")

# Convert to WGS 84 (EPSG:4326) for OSM compatibility
optimized_roads = optimized_roads.to_crs(epsg=4326)

# --- Step 5: Load Existing Road Network ---
existing_roads = gpd.read_file("existing_roads.geojson").to_crs(epsg=4326)

# --- Step 6: Convert to OSM Format ---
osm = Element("osm", version="0.6", generator="GeoPandas")

node_id = -1
nodes = {}

# Convert points to GeoSeries in WGS 84
points_wgs84 = gpd.GeoSeries([Point(p) for p in points], crs="EPSG:32643").to_crs(epsg=4326)

# --- Add Optimized Roads to OSM ---
for i, line in enumerate(optimized_roads.geometry):
    way = SubElement(osm, "way", id=str(-i - 1))

    for point in line.coords:
        point = Point(point)  # Ensure Point object
        point = gpd.GeoSeries([point], crs="EPSG:4326").geometry[0]  # Convert to WGS 84

        lat, lon = point.y, point.x
        if (lat, lon) not in nodes:
            nodes[(lat, lon)] = node_id
            node = SubElement(osm, "node", id=str(node_id), lat=str(lat), lon=str(lon))
            node_id -= 1

        nd = SubElement(way, "nd", ref=str(nodes[(lat, lon)]))

    SubElement(way, "tag", k="highway", v="unclassified")

# --- Add Existing Roads to OSM ---
for i, line in enumerate(existing_roads.geometry):
    way = SubElement(osm, "way", id=str(-100000 - i))  # Unique negative IDs

    for point in line.coords:
        point = Point(point)
        lat, lon = point.y, point.x  # Already in WGS 84

        if (lat, lon) not in nodes:
            nodes[(lat, lon)] = node_id
            node = SubElement(osm, "node", id=str(node_id), lat=str(lat), lon=str(lon))
            node_id -= 1

        nd = SubElement(way, "nd", ref=str(nodes[(lat, lon)]))

    SubElement(way, "tag", k="highway", v="secondary")  # Tag as secondary roads

# --- Add Building Clusters as Nodes ---
for i, point in enumerate(points_wgs84.geometry):
    lat, lon = point.y, point.x  # Ensure WGS 84 format

    node = SubElement(osm, "node", id=str(node_id), lat=str(lat), lon=str(lon))
    SubElement(node, "tag", k="amenity", v="building_cluster")

    node_id -= 1

# --- Save OSM File ---
osm_file = "optimized_roads_with_buildings.osm"
tree = ElementTree(osm)
tree.write(osm_file, encoding="utf-8", xml_declaration=True)

print(f"OSM file saved: {osm_file}")

# --- Step 7: Visualization ---
fig, ax = plt.subplots(figsize=(15, 12))

# Plot Existing Road Network in Gray
existing_roads.plot(ax=ax, color="gray", linewidth=0.5, label="Existing Roads")

# Plot Optimized Road Network in Blue
optimized_roads.plot(ax=ax, color="blue", linewidth=1.2, label="Optimized Roads")

# Plot Building Clusters as Nodes (Red Dots)
centroids.to_crs(epsg=4326).plot(ax=ax, color="red", markersize=5, label="Building Clusters")

ax.set_title("Optimized Road Network with Existing Roads & Building Clusters")
ax.legend()
ax.axis("off")
plt.show()

from google.colab import files
files.download("optimized_roads_with_buildings.osm")